apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: netflix-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 050752619291.dkr.ecr.us-east-1.amazonaws.com/netflix-frontend:v1
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://backend.netflix-clone.svc.cluster.local:5000"
          # volumeMounts removed to disable PVC/PV usage
      # volumes removed to disable PVC/PV usage