apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-shared-infra
  namespace: netflix-clone
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:Kebbak/Netflix-Replica-Full-Stack-Web-App-with-DevOps.git'
    path: K8s-Manifests/shared-infra
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
