apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-shared-infra
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/Kebba91/Netflix-Replica-Full-Stack-Web-App-with-DevOps'
    path: K8s-Manifests/infra
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true