resources:
  - ../../frontend/frontend-deployment.yaml
  - ../../frontend/service.yaml
  - ../../frontend/frontend-pv.yaml
  - ../../frontend/frontend-pvc.yaml

# patches:
#   - patch.yaml
#   - ../shared-infra/patch.yaml