# .github/workflows/trivy-scan.yaml
name: Trivy Image Scan (Manual)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to scan'
        required: true
        default: 'v1'

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE name
        run: echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
        env:
          IMAGE: "${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/netflix-backend:${{ github.event.inputs.image_tag }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull image from ECR
        run: docker pull $IMAGE

      - name: Scan Docker image with Trivy and generate HTML report
        run: |
          mkdir -p trivy-reports
          trivy image --severity CRITICAL,HIGH --format html --output trivy-reports/scan-report.html $IMAGE

      - name: Upload Trivy HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-reports/scan-report.html