apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-dashboard-cpu-memory
          mountPath: /etc/grafana/provisioning/dashboards/cpu-memory-dashboard.json
          subPath: cpu-memory-dashboard.json
        - name: grafana-dashboard-provisioning
          mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
          subPath: dashboards.yaml
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: grafana-dashboard-cpu-memory
        configMap:
          name: grafana-dashboard-cpu-memory
      - name: grafana-dashboard-provisioning
        configMap:
          name: grafana-dashboard-provisioning
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
